#!/usr/bin/env bash
# build-bundle.sh — produce the immutable standard bundle manifest.
#
#   ./tools/build-bundle.sh [--check]
#
# Writes bundle/manifest.json: the exact bytes of the standard a given
# evaluation ran against, addressed by digest. An engine records the digest in
# every receipt, which is what makes a receipt replayable — without it a receipt
# says which version it evaluated and not which content.
#
# --check regenerates into a temp file and diffs. Exit 6 if the committed
# manifest is stale. This is what CI runs.
#
# Determinism is the whole point, so: LC_ALL=C sort, no timestamps, no
# generator version, no host facts. The same tree produces the same digest on
# any machine, forever. A manifest carrying a build date would change every
# release for reasons unrelated to the standard's content.
set -euo pipefail

STANDARD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$STANDARD_DIR"

MODE="write"
[ "${1:-}" = "--check" ] && MODE="check"

VERSION="$(cat VERSION)"
RELEASED="$(cat RELEASED)"
SPINE_VERSION="$(sed -n 's/.*"spine_version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' gate/profiles.json | head -1)"
GATE_VERSION="$(sed -n 's/^\*\*Version:\*\*[[:space:]]*\(.*\)$/\1/p' gate/gate-configuration.md | head -1)"

# The bundle is exactly what sync.sh vendors, plus the manifest's own inputs.
# Kept in sync with sync.sh VENDORED by tools/validate.sh, which fails when the
# two lists diverge — a file vendored but not in the bundle is a file whose
# drift the digest would not catch.
BUNDLE_FILES=(
  "VERSION"
  "RELEASED"
  "AGENTS.md"
  "gate/profiles.json"
  "gate/checks.json"
  "gate/gate-configuration.md"
  "skills/decision-spine/SKILL.md"
  "skills/decision-spine/reference/spine.md"
  "skills/decision-spine/reference/gate-profiles.md"
  # How a system arrives at its tier and class. Digested because the gate reads
  # the two values it produces: a project that edited the escalators locally
  # would still be calling the result a criticality class while gate/profiles.json
  # resolved a profile from it. See ADR 0032.
  "skills/decision-spine/reference/placement.md"
  "skills/decision-spine/reference/managed-policy.md"
  "templates/managed-policy.json"
  "skills/decision-spine/reference/references.md"
  # The practitioner capture path. The skill defines what an interview may and
  # may not put in a practitioner's mouth, and the template defines the shape a
  # note has to reach before it can be promoted. Both are digested for the same
  # reason the ADR templates are: a project that quietly edited either one would
  # still be producing something it called a field note, and the promotion rules
  # in Build DNA's Practitioner role would be reading a different artifact than
  # the one they were written against. See ADR 0028.
  "skills/field-note/SKILL.md"
  # The intake instrument. Digested for the same reason as the field-note pair:
  # templates/survey.md defines the row IDs that ADR `survey_rows` and `forces`
  # cite, and the skill defines the readiness test those fields assume was run.
  # A project that quietly edited either would still be calling the result a
  # Survey while §8's rules read a different artifact. See ADR 0031.
  "skills/survey/SKILL.md"
  "templates/adr-template.md"
  "templates/adr-waiver-template.md"
  "templates/adr-retroactive-template.md"
  "templates/survey.md"
  "templates/field-note.md"
  "rules/security.md"
  "rules/secrets.md"
  "rules/database.md"
  "rules/tests.md"
  "rules/dependencies.md"
  "rules/inference.md"
  "tools/check-drift.sh"
  "tools/verify-release.sh"
  "tools/doctor.sh"
  "tools/field-notes.sh"
  "tools/impact.sh"
  # The trust anchor. Digested so it cannot be swapped without moving the
  # bundle digest — validate.py §13 fails if this is added and sync.sh is not,
  # or the file is named here and does not exist.
  "bundle/allowed-signers"
)

# Overlays are opt-in per project but are part of the standard's content, so
# they are digested here. A project that vendors no overlay still verifies
# against the same bundle digest as one that vendors all of them.
while IFS= read -r o; do
  [ "$(basename "$o" .md)" = "README" ] || BUNDLE_FILES+=("$o")
done < <(find overlays -name '*.md' | LC_ALL=C sort)

# The machine-readable projections are digested too. An overlay whose JSON could
# drift from its prose unnoticed is two overlays.
while IFS= read -r o; do
  BUNDLE_FILES+=("$o")
done < <(find overlays -name '*.json' | LC_ALL=C sort)

for f in "${BUNDLE_FILES[@]}"; do
  [ -f "$f" ] || { echo "bundle: missing file: $f" >&2; exit 1; }
done

# Canonical digest input: "<sha256>  <path>\n" per file, sorted by path.
DIGEST_INPUT="$(for f in "${BUNDLE_FILES[@]}"; do
  printf '%s  %s\n' "$(sha256sum "$f" | cut -d' ' -f1)" "$f"
done | LC_ALL=C sort -k2)"

BUNDLE_DIGEST="sha256:$(printf '%s\n' "$DIGEST_INPUT" | sha256sum | cut -d' ' -f1)"

emit_manifest() {
  printf '{\n'
  printf '  "$comment": "Generated by tools/build-bundle.sh. Do not edit by hand — CI regenerates and diffs.",\n'
  printf '  "standard": {\n'
  printf '    "id": "causeway",\n'
  printf '    "version": "%s",\n' "$VERSION"
  printf '    "released": "%s",\n' "$RELEASED"
  printf '    "spine_version": "%s",\n' "$SPINE_VERSION"
  printf '    "gate_config_version": "%s"\n' "$GATE_VERSION"
  printf '  },\n'
  printf '  "digest": "%s",\n' "$BUNDLE_DIGEST"
  printf '  "digest_algorithm": "sha256-of-sorted-file-digest-lines",\n'
  printf '  "files": [\n'
  local first=1
  while IFS= read -r line; do
    local sum path
    sum="${line%% *}"
    path="${line##*  }"
    [ $first -eq 1 ] || printf ',\n'
    first=0
    printf '    { "path": "%s", "sha256": "%s" }' "$path" "$sum"
  done <<< "$DIGEST_INPUT"
  printf '\n  ]\n'
  printf '}\n'
}

if [ "$MODE" = "check" ]; then
  TMP="$(mktemp)"
  trap 'rm -f "$TMP"' EXIT
  emit_manifest > "$TMP"
  if ! diff -q bundle/manifest.json "$TMP" >/dev/null 2>&1; then
    echo "bundle/manifest.json is stale — run ./tools/build-bundle.sh" >&2
    diff -u bundle/manifest.json "$TMP" >&2 || true
    exit 6
  fi
  echo "bundle/manifest.json current — $BUNDLE_DIGEST"
  exit 0
fi

mkdir -p bundle
emit_manifest > bundle/manifest.json
echo "Causeway bundle v$VERSION ($RELEASED)"
echo "  spine $SPINE_VERSION · gate config $GATE_VERSION · ${#BUNDLE_FILES[@]} files"
echo "  $BUNDLE_DIGEST"
